- update application.properties - add necessary dependencies - add package structure
sergei-gots/pet-shelter-bot pull request #1
Opened 2023-06-27 17:24 UTC by ATsarev01

2023-06-27 17:44 UTC, Sergei-Gots reviewed
Есть один нюанс. Оказывается, пустые директории не пушатся. ок

2023-06-27 17:46 UTC, Sergei-Gots commented
отсутствует класс TelegramBotListener, и его функциональность

2023-06-29 18:23 UTC, Sergei-Gots requested changes

2023-06-29 18:23 UTC, sergei-gots commented on src/main/resources/application-dev.properties
Антон, привет! Этот файл не должен включаться в git-repository. Иначе он за-commit-ится в очередной раз, и будет содержать токен, а также, возможно, другие всякие sensitive data.

2023-06-29 18:23 UTC, sergei-gots commented on src/main/java/pro/sky/petshelterbot/listener/TelegramBotListener.java
> +        if (message.text() != null && message.text().equals("/start")) {
Тут следует добавить log-ирование.

2023-06-29 18:23 UTC, sergei-gots commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/pet-shelter-bot
следует заменить символы '-' в названии database на классические '_' (поменять название db на pet_shelter_bot)

2023-06-29 18:39 UTC, ATsarev01 commented on src/main/resources/application-dev.properties
Done

2023-06-29 18:40 UTC, ATsarev01 commented on src/main/java/pro/sky/petshelterbot/listener/TelegramBotListener.java
> +        if (message.text() != null && message.text().equals("/start")) {
Done

2023-06-29 18:40 UTC, ATsarev01 commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/pet-shelter-bot
Done

2023-06-30 14:16 UTC, sergei-gots requested changes

2023-06-30 14:16 UTC, sergei-gots commented on src/main/java/pro/sky/petshelterbot/listener/TelegramBotListener.java
> +        updates.forEach(update -> {
Привет! Здесь нужно обернуть всё в try-catch

2023-06-30 14:16 UTC, sergei-gots commented on src/main/java/pro/sky/petshelterbot/listener/TelegramBotListener.java
> +            String firstName = message.chat().firstName();
Прежде всего, инфо-лог должен содержать название метода. то есть начинаться, например, с "processMessage-method. "  Затем, следует разместить этот лог в самом начале метода, помимо прочего это сделает код читабельнее, избавит от дублирования. не нужна будет ветка else. Далее, ты распечатываешь, что получено сообщение  от такого-то пользователя. Будет лучше, если ты в начале распечатаешь более конкретную информацию - а именно  - id. Этот мой комментарий относится ко всем логам, так что просмотри их локализацию в методах и содержимое  по всему коду

2023-06-30 14:16 UTC, sergei-gots commented on src/main/java/pro/sky/petshelterbot/listener/TelegramBotListener.java
> +            logger.info("Received message from user: " + message.text());
лучше разместить лог в самом начале метода, это сделает код читабельнее, избавит от дублирования. не нужна будет ветка else

2023-07-01 09:20 UTC, Sergei-Gots approved these changes

2023-07-01 09:21 UTC, merged